import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {
  initialCoreState, validateCoreState, evaluateHeartbeat, coreSummary, coreHomeSummary,
  createCoreIdentity, ACTIVITY_STATES, HEARTBEAT_TRIGGERS, CORE_SCHEMA_VERSION, BlackholeCoreError,
} from '../lib/blackhole-core.mjs';
import {
  createMemoryEvent, validateMemoryEvent, validateMemoryEvents, addMemoryEvent,
  MEMORY_EVENT_TYPES, MemoryEventError, MAX_MEMORY_EVENTS,
} from '../lib/memory-events.mjs';
import {OutcomeVerificationError} from '../lib/outcome-verification.mjs';

// BLACKHOLE Living Core, Phase A — persistent self + event-driven heartbeat +
// canonical Memory Event primitive. These are pure-function tests against the
// exact projection/validation logic store.mjs and server.mjs wire in; the
// restart-persistence and emergency-stop behaviour are covered end-to-end in
// blackhole-core-server.test.mjs against the real store/server.

const at = () => new Date().toISOString();
function baseState(overrides = {}) {
  return {emergencyStop: false, jobs: [], quests: [], projects: [], outcomes: [], sources: [], capabilities: {entries: []}, memoryEvents: [], ...overrides};
}
function project(id, overrides = {}) {
  const t = at();
  return {id, name: 'P', repositoryUrl: '', summary: '', nextAction: '', status: 'active', version: 1, createdAt: t, updatedAt: t, ...overrides};
}
function quest(id, jobId, overrides = {}) {
  const t = at();
  return {id, driveId: 'sloth', drive: 'sloth', projectId: null, status: 'queued', jobId, updatedAt: t, createdAt: t, goal: 'g', successCriterion: 's', baseline: 'b', ...overrides};
}
function job(id, overrides = {}) {
  const t = at();
  return {id, status: 'queued', updatedAt: t, createdAt: t, artifacts: [], ...overrides};
}

test('initialCoreState is idle, empty and validates against an empty state', () => {
  const state = baseState();
  const core = initialCoreState();
  assert.equal(core.schemaVersion, CORE_SCHEMA_VERSION);
  assert.equal(core.activity, 'idle');
  assert.equal(core.missionQuestId, null);
  assert.equal(core.dominantDriveId, null);
  assert.deepEqual(core.activeShadowIds, []);
  assert.equal(core.recentArtifactRef, null);
  assert.equal(core.verifiedResultRef, null);
  assert.equal(core.heartbeatCount, 0);
  assert.equal(core.lastHeartbeatAt, null);
  validateCoreState(core, state);
});

test('a stable Persistent Self identity is generated once and never regenerated by later heartbeats', () => {
  const state = baseState();
  const core0 = initialCoreState('2026-01-01T00:00:00.000Z');
  assert.match(core0.identity.id, /^[0-9a-f-]{36}$/);
  assert.equal(core0.identity.name, 'BLACKHOLE');
  assert.equal(core0.identity.createdAt, '2026-01-01T00:00:00.000Z');
  validateCoreState(core0, state);

  const {core: core1} = evaluateHeartbeat(core0, state, {at: '2026-01-01T00:01:00.000Z'});
  assert.deepEqual(core1.identity, core0.identity, 'identity must survive an ordinary heartbeat unchanged');
  const {core: core2} = evaluateHeartbeat(core1, state, {at: '2026-01-01T00:02:00.000Z', trigger: 'owner_command'});
  assert.deepEqual(core2.identity, core0.identity, 'identity must survive across many heartbeats and triggers unchanged');

  // Two independently created identities must never collide.
  const other = createCoreIdentity('2026-01-01T00:00:00.000Z');
  assert.notEqual(other.id, core0.identity.id);
});

test('validateCoreState rejects a tampered or malformed identity', () => {
  const state = baseState();
  const core = initialCoreState();
  assert.throws(() => validateCoreState({...core, identity: {...core.identity, id: 'not-a-uuid'}}, state), BlackholeCoreError);
  assert.throws(() => validateCoreState({...core, identity: {...core.identity, name: ''}}, state), BlackholeCoreError);
  assert.throws(() => validateCoreState({...core, identity: {...core.identity, createdAt: 'not-a-date'}}, state), BlackholeCoreError);
  assert.throws(() => validateCoreState({...core, identity: {id: core.identity.id}}, state), BlackholeCoreError, 'missing identity fields must fail closed');
});

test('every taxonomy activity is accepted by validation even though Phase A only ever produces idle/executing/emergency', () => {
  assert.deepEqual([...ACTIVITY_STATES].sort(), ['absorbing', 'blocked', 'emergency', 'executing', 'idle', 'leveling', 'listening', 'offline', 'planning', 'remembering', 'thinking', 'verifying'].sort());
  const state = baseState();
  for (const activity of ACTIVITY_STATES) {
    const core = {...initialCoreState(), activity};
    validateCoreState(core, state);
  }
});

test('heartbeat derives executing only from a real running job, idle otherwise, emergency whenever emergencyStop is true regardless of jobs', () => {
  const idleState = baseState();
  const {core: idleCore} = evaluateHeartbeat(initialCoreState(), idleState, {at: at()});
  assert.equal(idleCore.activity, 'idle');

  const runningState = baseState({jobs: [job(randomUUID(), {status: 'running'})]});
  const {core: runningCore} = evaluateHeartbeat(initialCoreState(), runningState, {at: at()});
  assert.equal(runningCore.activity, 'executing');

  const emergencyState = baseState({emergencyStop: true, jobs: [job(randomUUID(), {status: 'running'})]});
  const {core: emergencyCore} = evaluateHeartbeat(initialCoreState(), emergencyState, {at: at()});
  assert.equal(emergencyCore.activity, 'emergency');
});

test('mission/focusProject/dominantDriveId derive only from a live (queued/running/paused) quest, never a completed/cancelled/failed one, and are null when nothing is live', () => {
  const projectId = randomUUID(), jobId = randomUUID(), questId = randomUUID();
  for (const status of ['completed', 'failed', 'cancelled']) {
    const state = baseState({
      projects: [project(projectId)],
      jobs: [job(jobId, {status: 'completed', artifacts: [{id: 'a1', name: 'a'}]})],
      quests: [quest(questId, jobId, {status, projectId, driveId: 'wrath'})],
    });
    const {core} = evaluateHeartbeat(initialCoreState(), state, {at: at()});
    assert.equal(core.missionQuestId, null, `status ${status} must not be a live mission`);
    assert.equal(core.dominantDriveId, null);
  }
  for (const status of ['queued', 'running', 'paused']) {
    const state = baseState({
      projects: [project(projectId)],
      jobs: [job(jobId, {status: status === 'queued' ? 'queued' : status})],
      quests: [quest(questId, jobId, {status, projectId, driveId: 'envy'})],
    });
    const {core} = evaluateHeartbeat(initialCoreState(), state, {at: at()});
    assert.equal(core.missionQuestId, questId);
    assert.equal(core.focusProjectId, projectId);
    assert.equal(core.dominantDriveId, 'envy', 'dominant drive is the mission quest\'s own already-assigned driveId, never scored here');
    validateCoreState(core, state);
  }
});

test('the most recently updated live quest wins as the mission, never an arbitrary or first one', () => {
  const older = quest(randomUUID(), randomUUID(), {status: 'queued', updatedAt: '2026-01-01T00:00:00.000Z', driveId: 'greed'});
  const newer = quest(randomUUID(), randomUUID(), {status: 'paused', updatedAt: '2026-06-01T00:00:00.000Z', driveId: 'pride'});
  const state = baseState({quests: [older, newer], jobs: [job(older.jobId, {status: 'queued'}), job(newer.jobId, {status: 'paused'})]});
  const {core} = evaluateHeartbeat(initialCoreState(), state, {at: at()});
  assert.equal(core.missionQuestId, newer.id);
  assert.equal(core.dominantDriveId, 'pride');
});

test('active shadows are only real running project-bot jobs, never queued/paused ones and never a decorative count', () => {
  const running = job(randomUUID(), {status: 'running', botAssignment: {profile: 'primary'}});
  const paused = job(randomUUID(), {status: 'paused', botAssignment: {profile: 'primary'}});
  const runningNonBot = job(randomUUID(), {status: 'running'});
  const state = baseState({jobs: [running, paused, runningNonBot]});
  const {core} = evaluateHeartbeat(initialCoreState(), state, {at: at()});
  assert.deepEqual(core.activeShadowIds, [running.id]);
  validateCoreState(core, state);
});

test('recentArtifactRef is only the most recently updated completed quest job that actually carries an artifact - and is never called verified', () => {
  const olderJobId = randomUUID(), olderQuestId = randomUUID();
  const newerJobId = randomUUID(), newerQuestId = randomUUID();
  const noArtifactJobId = randomUUID(), noArtifactQuestId = randomUUID();
  const state = baseState({
    jobs: [
      job(olderJobId, {status: 'completed', updatedAt: '2026-01-01T00:00:00.000Z', artifacts: [{id: 'old-art', name: 'a'}]}),
      job(newerJobId, {status: 'completed', updatedAt: '2026-06-01T00:00:00.000Z', artifacts: [{id: 'new-art', name: 'a'}]}),
      job(noArtifactJobId, {status: 'completed', updatedAt: '2026-09-01T00:00:00.000Z', artifacts: []}),
    ],
    quests: [
      quest(olderQuestId, olderJobId, {status: 'completed'}),
      quest(newerQuestId, newerJobId, {status: 'completed'}),
      quest(noArtifactQuestId, noArtifactJobId, {status: 'completed'}),
    ],
  });
  const {core} = evaluateHeartbeat(initialCoreState(), state, {at: at()});
  assert.deepEqual(core.recentArtifactRef, {type: 'quest', questId: newerQuestId, jobId: newerJobId, artifactId: 'new-art'});
  // A completed job with an attached artifact is integrity evidence only
  // (quests.mjs's own "artifact_recorded"), never a verified outcome: no
  // durable outcome-verification verdict store exists anywhere in this
  // codebase yet for a real verified result to reference.
  assert.equal(core.verifiedResultRef, null, 'completed+artifact alone must never populate a verified result');
  validateCoreState(core, state);
});

test('verifiedResultRef can never be non-null: validateCoreState fails closed the moment anything tries to populate it', () => {
  const state = baseState();
  const core = initialCoreState();
  assert.throws(
    () => validateCoreState({...core, verifiedResultRef: {type: 'quest', questId: randomUUID(), jobId: randomUUID(), artifactId: 'x'}}, state),
    BlackholeCoreError,
    'no durable outcome-verification verdict store exists yet, so this must always fail closed',
  );
});

test('relationshipMemoryPointer is re-derived fresh every heartbeat from the most recent relationship memory event, never an independently settable field', () => {
  const state = baseState();
  const older = createMemoryEvent({type: 'relationship', text: '첫 상호작용', confidence: 0.5, projectId: null, questId: null, sourceRefs: []}, state, {at: '2026-01-01T00:00:00.000Z'});
  state.memoryEvents = addMemoryEvent(state.memoryEvents, older, state);
  const {core: core1} = evaluateHeartbeat(initialCoreState(), state, {at: at()});
  assert.equal(core1.relationshipMemoryPointer, older.id);

  const newer = createMemoryEvent({type: 'relationship', text: '더 최근 상호작용', confidence: 0.5, projectId: null, questId: null, sourceRefs: []}, state, {at: '2026-06-01T00:00:00.000Z'});
  state.memoryEvents = addMemoryEvent(state.memoryEvents, newer, state);
  const {core: core2} = evaluateHeartbeat(core1, state, {at: at()});
  assert.equal(core2.relationshipMemoryPointer, newer.id);
  validateCoreState(core2, state);
});

test('heartbeatLog is bounded and always keeps the most recent entries, never grows unbounded', () => {
  const state = baseState();
  let core = initialCoreState();
  for (let i = 0; i < 30; i++) {
    core = evaluateHeartbeat(core, state, {at: new Date(Date.now() + i * 1000).toISOString()}).core;
  }
  assert.equal(core.heartbeatCount, 30);
  assert.ok(core.heartbeatLog.length <= 20);
  assert.equal(core.heartbeatLog.length, 20);
  validateCoreState(core, state);
});

test('heartbeat entries record an explicit wake trigger, separate from the changed-fields reason, defaulting to the honest state_changed', () => {
  const state = baseState();
  const {entry: defaultEntry} = evaluateHeartbeat(initialCoreState(), state, {at: at()});
  assert.equal(defaultEntry.trigger, 'state_changed', 'omitting trigger must fall back to the honest default, never imply a specific cause it was not given');

  for (const trigger of HEARTBEAT_TRIGGERS) {
    const {entry, core} = evaluateHeartbeat(initialCoreState(), state, {at: at(), trigger});
    assert.equal(entry.trigger, trigger);
    validateCoreState(core, state);
  }

  assert.throws(() => evaluateHeartbeat(initialCoreState(), state, {at: at(), trigger: 'not_a_real_trigger'}), BlackholeCoreError);
});

test('the wake trigger (why it woke) is independent of the reason/changedFields (what it noticed): a real state change under runtime_started still names runtime_started', () => {
  const jobId = randomUUID();
  const state = baseState({jobs: [job(jobId, {status: 'running'})]});
  const {entry} = evaluateHeartbeat(initialCoreState(), state, {at: at(), trigger: 'runtime_started'});
  assert.equal(entry.trigger, 'runtime_started');
  assert.ok(entry.changedFields.includes('activity'), 'the projection still records what changed');
  assert.match(entry.reason, /changed: activity/);

  // And a no-op heartbeat under a real trigger still names that trigger,
  // never manufacturing a change that did not happen.
  const core1 = evaluateHeartbeat(initialCoreState(), state, {at: at(), trigger: 'runtime_started'}).core;
  const {entry: entry2} = evaluateHeartbeat(core1, state, {at: at(), trigger: 'owner_command'});
  assert.equal(entry2.trigger, 'owner_command');
  assert.equal(entry2.reason, 'observed, no change');
});

test('validateCoreState rejects a heartbeat log entry with an unknown or missing trigger', () => {
  const state = baseState();
  const core = initialCoreState();
  const {core: withEntry} = evaluateHeartbeat(core, state, {at: at(), trigger: 'runtime_started'});
  const tamperedLog = [{...withEntry.heartbeatLog[0], trigger: 'not_a_real_trigger'}];
  assert.throws(() => validateCoreState({...withEntry, heartbeatLog: tamperedLog}, state), BlackholeCoreError);
});

test('validateCoreState fails closed on tampering: dominant drive disagreeing with the mission, a dangling mission/project/shadow reference, and an inconsistent heartbeat counter', () => {
  const projectId = randomUUID(), jobId = randomUUID(), questId = randomUUID();
  const state = baseState({
    projects: [project(projectId)],
    jobs: [job(jobId, {status: 'queued'})],
    quests: [quest(questId, jobId, {status: 'queued', projectId, driveId: 'lust'})],
  });
  const {core} = evaluateHeartbeat(initialCoreState(), state, {at: at()});
  validateCoreState(core, state);

  assert.throws(() => validateCoreState({...core, dominantDriveId: 'wrath'}, state), BlackholeCoreError);
  assert.throws(() => validateCoreState({...core, missionQuestId: randomUUID()}, state), BlackholeCoreError);
  assert.throws(() => validateCoreState({...core, focusProjectId: randomUUID()}, state), BlackholeCoreError);
  assert.throws(() => validateCoreState({...core, activeShadowIds: [randomUUID()]}, state), BlackholeCoreError);
  assert.throws(() => validateCoreState({...core, activeShadowIds: [jobId, jobId]}, state), BlackholeCoreError, 'duplicate shadow ids must be rejected even if the id is real');
  assert.throws(() => validateCoreState({...core, heartbeatCount: 0}, state), BlackholeCoreError, 'lastHeartbeatAt set but heartbeatCount 0 is inconsistent');
  assert.throws(() => validateCoreState({...core, activity: 'not-a-real-activity'}, state), BlackholeCoreError);
  assert.throws(() => validateCoreState({...core, extraField: true}, state), BlackholeCoreError, 'unexpected field must fail closed');
});

test('coreSummary and coreHomeSummary never fabricate a field: every value traces to the stored Core record or a real referenced quest/project/memory event', () => {
  const projectId = randomUUID(), jobId = randomUUID(), questId = randomUUID();
  const state = baseState({
    projects: [project(projectId, {name: '실제 프로젝트'})],
    jobs: [job(jobId, {status: 'running'})],
    quests: [quest(questId, jobId, {status: 'running', projectId, driveId: 'gluttony', goal: '실제 목표'})],
  });
  state.blackholeCore = evaluateHeartbeat(initialCoreState(), state, {at: at()}).core;
  const summary = coreSummary(state);
  assert.equal(summary.activity, 'executing');
  assert.equal(summary.identity.name, 'BLACKHOLE');
  assert.equal(summary.mission.goal, '실제 목표');
  assert.equal(summary.focusProject.name, '실제 프로젝트');
  assert.equal(summary.dominantDriveId, 'gluttony');
  assert.equal(typeof summary.dominantDriveName, 'string');
  assert.equal(summary.dominantDriveWorldName, '지식');
  assert.equal(summary.verifiedResult, null, 'verifiedResult must never be fabricated from an artifact');

  const home = coreHomeSummary(state);
  assert.equal(home.activity, 'executing');
  assert.equal(home.missionGoal, '실제 목표');
  assert.equal(home.focusProjectName, '실제 프로젝트');
  assert.equal(home.dominantDriveId, 'gluttony');
  assert.equal(home.dominantDriveWorldName, '지식');
  assert.equal(home.verifiedResult, null);

  // No live mission: placeholders are null, never a fabricated drive/goal.
  const empty = baseState();
  empty.blackholeCore = initialCoreState();
  const emptyHome = coreHomeSummary(empty);
  assert.equal(emptyHome.missionGoal, null);
  assert.equal(emptyHome.dominantDriveId, null);
  assert.equal(emptyHome.dominantDriveName, null);
  assert.equal(emptyHome.dominantDriveWorldName, null);
  assert.equal(emptyHome.recentArtifactResult, null);
});

// --- Memory Event primitive ---

test('createMemoryEvent produces a self-consistent, referentially valid record for every declared type', () => {
  const projectId = randomUUID(), jobId = randomUUID(), questId = randomUUID();
  const state = baseState({
    projects: [project(projectId)],
    jobs: [job(jobId, {status: 'completed'})],
    quests: [quest(questId, jobId, {status: 'completed'})],
  });
  for (const type of MEMORY_EVENT_TYPES) {
    const claim = {type, text: `${type} 기억`, confidence: 0.7, projectId, questId, sourceRefs: [{type: 'quest', id: questId}, {type: 'job', id: jobId}, {type: 'project', id: projectId}]};
    const event = createMemoryEvent(claim, state, {at: at()});
    validateMemoryEvent(event, state);
    assert.equal(event.type, type);
  }
});

test('memory events reject secrets in text, dangling source references, out-of-range confidence, and tampering', () => {
  const state = baseState();
  const claim = {type: 'episode', text: 'ordinary text', confidence: 0.5, projectId: null, questId: null, sourceRefs: []};

  // Redaction is the exact reused assertNoSecrets from outcome-verification.mjs
  // (never reimplemented), so it throws its own error type, unwrapped - the
  // same behaviour solo-leveling.mjs's validateSkillHistory already relies on.
  assert.throws(() => createMemoryEvent({...claim, text: 'sk-abcdefghijklmnopqrstuvwx'}, state, {at: at()}), OutcomeVerificationError);
  assert.throws(() => createMemoryEvent({...claim, sourceRefs: [{type: 'job', id: randomUUID()}]}, state, {at: at()}), MemoryEventError);
  assert.throws(() => createMemoryEvent({...claim, confidence: 1.5}, state, {at: at()}), MemoryEventError);
  assert.throws(() => createMemoryEvent({...claim, confidence: -0.1}, state, {at: at()}), MemoryEventError);
  assert.throws(() => createMemoryEvent({...claim, type: 'not-a-real-type'}, state, {at: at()}), MemoryEventError);

  const event = createMemoryEvent(claim, state, {at: at()});
  assert.throws(() => validateMemoryEvent({...event, text: 'changed after fingerprinting'}, state), MemoryEventError);
  assert.throws(() => validateMemoryEvent({...event, confidence: 0.9}, state), MemoryEventError);
});

test('duplicate source references within one event are rejected even when each reference is individually real', () => {
  const jobId = randomUUID();
  const state = baseState({jobs: [job(jobId, {status: 'completed'})]});
  const claim = {type: 'episode', text: 't', confidence: 0.5, projectId: null, questId: null, sourceRefs: [{type: 'job', id: jobId}, {type: 'job', id: jobId}]};
  assert.throws(() => createMemoryEvent(claim, state, {at: at()}), MemoryEventError);
});

test('addMemoryEvent enforces the capacity bound and validateMemoryEvents rejects a duplicate id', () => {
  const state = baseState();
  const claim = {type: 'episode', text: 't', confidence: 0.5, projectId: null, questId: null, sourceRefs: []};
  const event = createMemoryEvent(claim, state, {at: at()});
  const full = Array.from({length: MAX_MEMORY_EVENTS}, () => event);
  assert.throws(() => addMemoryEvent(full, event, state), MemoryEventError);
  assert.throws(() => validateMemoryEvents([event, event], state), MemoryEventError);
});

test('a capability sourceRef must reference a real, already-imported capability registry entry', () => {
  const state = baseState({capabilities: {entries: [{id: 'evidence-gap-brief'}]}});
  const claim = {type: 'skill', text: '이 기능을 성공적으로 사용함', confidence: 0.9, projectId: null, questId: null, sourceRefs: [{type: 'capability', id: 'evidence-gap-brief'}]};
  const event = createMemoryEvent(claim, state, {at: at()});
  validateMemoryEvent(event, state);
  assert.throws(() => createMemoryEvent({...claim, sourceRefs: [{type: 'capability', id: 'never-imported'}]}, state, {at: at()}), MemoryEventError);
});
