import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {randomUUID,randomBytes} from 'node:crypto';
import {start} from '../server.mjs';import {openStore,digest} from '../lib/store.mjs';import {exportBackup,restoreBackup} from '../lib/backup.mjs';
const fixtures=[{name:'합계',input:[2,4],expected:6},{name:'빈값',input:[],expected:0}];
const env={YENO_AGENT_PROVIDER:'openai',YENO_AGENT_DAILY_CALL_LIMIT:'20',YENO_OPENAI_MODEL:'synthetic-code-model',YENO_OPENAI_API_KEY:'synthetic-code-key'};
const reply=content=>new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:typeof content==='string'?content:JSON.stringify(content)}}],usage:{prompt_tokens:20,completion_tokens:50}}),{headers:{'Content-Type':'application/json'}});
const source=(body='return x.reduce((a,b)=>a+b,0)')=>({files:[{path:'main.mjs',content:`export function run(x){${body}}`}],entry:'main.mjs',fixtures});
async function harness(t,options={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),'blackhole-code-api-')),dataDir=path.join(root,'data'),token='synthetic-code-owner-secret';const st=openStore(dataDir);st.state.modules.ai=options.ai!==false;st.save();let core=await start({dataDir,host:'127.0.0.1',port:0,token,env,...options});
const api=async(route,body)=>{const r=await fetch(`http://127.0.0.1:${core.server.address().port}${route}`,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const bytes=Buffer.from(await r.arrayBuffer());let value;try{value=JSON.parse(bytes);}catch{value=bytes.toString();}return {status:r.status,value,bytes};};
const post=(action,body)=>api('/api/code/'+action,{requestId:randomUUID(),...body});
const wait=async id=>{for(let i=0;i<400;i++){const s=(await api('/api/state')).value,j=s.jobs.find(j=>j.id===id);if(['completed','failed','paused','cancelled'].includes(j?.status))return j;await new Promise(r=>setTimeout(r,20));}throw Error('job timeout');};
t.after(()=>{core.shutdown();fs.rmSync(root,{recursive:true,force:true});});return {root,dataDir,api,post,wait,shutdown:()=>core.shutdown(),restart:async()=>{core.shutdown();core=await start({dataDir,host:'127.0.0.1',port:0,token,env,...options});}};}
test('native code worker really writes, tests failed candidate, repairs with immutable criteria and activates/reuses result',async t=>{
let calls=0;const h=await harness(t,{agentFetch:async(url,r)=>{calls++;const payload=JSON.parse(r.body);assert.equal(payload.tools,undefined);assert.match(payload.messages[0].content,/capability developer/);if(calls===1)return reply(source('return 0'));assert.match(payload.messages.at(-1).content,/Actual runtime test failed/);return reply(source());}});
const body={requestId:randomUUID(),id:'sum-values',name:'합계 능력',goal:'숫자 배열의 합계를 반환해줘',fixtures,activate:true};const accepted=await h.api('/api/code/generate',body);assert.equal(accepted.status,201);assert.equal((await h.api('/api/code/generate',body)).value.jobId,accepted.value.jobId);
const job=await h.wait(accepted.value.jobId);assert.equal(job.status,'completed',JSON.stringify(job));assert.equal(calls,2);assert.equal(job.code.passed,true);assert.equal(job.code.feedback.length,1);assert.equal(job.codeTask,undefined);assert.equal(job.artifacts.length,2);
let s=(await h.api('/api/state')).value;assert.equal(s.agent.usage.attempts,2);assert.ok(s.codeWorkshop.entries[0].activeHash);const run=await h.post('run',{id:'sum-values',input:[10,15,20]});const done=await h.wait(run.value.jobId);assert.equal(done.status,'completed');const out=await h.api('/api/artifacts/'+done.artifacts.find(a=>a.name.endsWith('.json')).id);assert.equal(out.value,45);assert.equal(calls,2);
await h.restart();assert.equal((await h.api('/api/artifacts/'+done.artifacts.find(a=>a.name.endsWith('.json')).id)).value,45);assert.equal((await h.api('/api/code')).value.entries[0].runCount,1);
h.shutdown();const stored=openStore(h.dataDir).state,key=randomBytes(32),archive=exportBackup({state:stored,dataDir:h.dataDir,key});restoreBackup({archive,key,targetDir:path.join(h.root,'restored')});const restored=openStore(path.join(h.root,'restored')).state;assert.equal(restored.codeWorkshop.entries[0].activeHash,null);assert.equal(restored.jobs.length,stored.jobs.length);assert.equal(digest(fs.readFileSync(path.join(h.root,'restored','artifacts',stored.artifacts[done.artifacts[1].id].filename))),digest(out.bytes));
});
test('AI-off and stop reject code spending; failed two repairs never replace working code',async t=>{
let calls=0;const h=await harness(t,{ai:false,agentFetch:async()=>{calls++;return reply(source('return 7'));}});
assert.equal((await h.post('generate',{goal:'더하기',fixtures})).status,409);assert.equal((await h.api('/api/voice',{requestId:randomUUID(),text:'안녕',history:[]})).status,409);assert.equal(calls,0);
await h.api('/api/settings',{requestId:randomUUID(),modules:{ai:true}});const r=await h.post('generate',{goal:'합계',id:'bad-code',fixtures});assert.equal(r.status,201);const j=await h.wait(r.value.jobId);assert.equal(j.status,'failed');assert.equal(j.artifacts.length,2);assert.equal((await h.api('/api/code')).value.entries.length,0);assert.equal(calls,2);
await h.api('/api/control',{requestId:randomUUID(),action:'stop'});assert.equal((await h.post('generate',{goal:'더하기',fixtures})).status,409);
});
test('voice keeps conversation context, returns actual provider answer in one bounded call and receipt replays',async t=>{
let calls=0;const h=await harness(t,{agentFetch:async(url,r)=>{calls++;const payload=JSON.parse(r.body);assert.equal(payload.tools,undefined);assert.match(payload.messages.at(-1).content,/지난 질문/);return reply('실제 합성 제공자 답변');}});
const b={requestId:randomUUID(),text:'그 다음은?',history:[{role:'user',content:'지난 질문'},{role:'assistant',content:'지난 답'}]};const r=await h.api('/api/voice',b);assert.equal(r.status,201);assert.equal((await h.api('/api/voice',b)).value.jobId,r.value.jobId);const j=await h.wait(r.value.jobId);assert.equal(j.status,'completed');assert.equal(calls,1);const file=await h.api('/api/artifacts/'+j.artifacts[0].id);assert.equal(file.value,'실제 합성 제공자 답변');await h.restart();assert.equal((await h.api('/api/artifacts/'+j.artifacts[0].id)).value,file.value);
});
test('stop during actual code generation aborts model, retains unknown reservation and cannot duplicate on resume',async t=>{
let started;const seen=new Promise(r=>started=r);let calls=0;const h=await harness(t,{agentFetch:async(url,req)=>{calls++;started();await new Promise((resolve,reject)=>req.signal.addEventListener('abort',()=>reject(Error('synthetic abort')),{once:true}));}});
const r=await h.post('generate',{goal:'합계',fixtures});await seen;await h.api('/api/control',{requestId:randomUUID(),action:'stop'});const j=await h.wait(r.value.jobId);assert.equal(j.status,'paused');await new Promise(r=>setTimeout(r,40));assert.equal((await h.api('/api/state')).value.agent.usage.unknown,1);assert.equal(calls,1);
});
