import './style.css';
import { fetch } from '@tauri-apps/plugin-http';
import { appDataDir, join } from '@tauri-apps/api/path';
import { Stronghold } from '@tauri-apps/plugin-stronghold';

type Job={id:string;title:string;status:string;version:number;updatedAt:string;artifacts:{id:string;name:string}[]};
type State={name:string;apiVersion:string;revision:number;emergencyStop:boolean;jobs:Job[]};
type Connection={origin:string;deviceId:string;token:string};
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const encoder=new TextEncoder(),decoder=new TextDecoder();
let connection:Connection|null=null,state:State|null=null,refreshTimer=0;
const requestKey='yeno.pending-command.v1';
const vaultMarker='yeno.native-vault.v1';
let vaultPassword:string|null=null;

async function vault(){if(!vaultPassword)throw new Error('보관소 암호가 필요합니다.');const path=await join(await appDataDir(),'controller.hold');const stronghold=await Stronghold.load(path,vaultPassword);let client;try{client=await stronghold.loadClient('controller');}catch{client=await stronghold.createClient('controller');}return {stronghold,store:client.getStore()};}
async function saveConnection(value:Connection|null){const v=await vault();if(value)await v.store.insert('connection',Array.from(encoder.encode(JSON.stringify(value))));else await v.store.remove('connection');await v.stronghold.save();}
async function loadConnection(){const v=await vault(),bytes=await v.store.get('connection');return bytes?JSON.parse(decoder.decode(new Uint8Array(bytes))) as Connection:null;}
function normalizeOrigin(raw:string){const url=new URL(raw);if(url.username||url.password||url.search||url.hash||!['https:','http:'].includes(url.protocol))throw new Error('HTTPS 코어 주소를 입력하세요.');if(url.protocol!=='https:'&&!['localhost','127.0.0.1'].includes(url.hostname))throw new Error('원격 코어는 HTTPS가 필요합니다.');return url.origin;}
async function api<T>(path:string,init:RequestInit={}):Promise<T>{if(!connection)throw new Error('기기가 연결되지 않았습니다.');const response=await fetch(`${connection.origin}/api/v1${path}`,{...init,headers:{authorization:`Bearer ${connection.token}`,...(init.body?{'content-type':'application/json'}:{}),...init.headers},connectTimeout:10_000});const data=await response.json().catch(()=>({error:`HTTP ${response.status}`}));if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data;}
function requestId(){return crypto.randomUUID();}
function showMessage(value=''){$('message').textContent=value;}
function render(){const connected=!!connection,locked=!connected&&localStorage.getItem(vaultMarker)==='present';$('unlock').hidden=!locked;$('setup').hidden=connected||locked;$('cockpit').hidden=!connected;$('connection').textContent=connected?'코어 연결됨':'연결 안 됨';if(!state)return;$('headline').textContent=state.emergencyStop?'전체 멈춤':'코어가 작업을 계속하고 있습니다';$('seen').textContent=`서버 상태 · ${new Date().toLocaleString()} · revision ${state.revision}`;$('stop').textContent=state.emergencyStop?'전체 멈춤 해제':'전체 멈춤';$('jobs').replaceChildren(...state.jobs.map(job=>{const node=document.createElement('article');node.className='job';const title=document.createElement('strong');title.textContent=job.title;const meta=document.createElement('p');meta.textContent=`${job.status} · ${new Date(job.updatedAt).toLocaleString()}`;node.append(title,meta);for(const artifact of job.artifacts){const button=document.createElement('button');button.className='artifact';button.textContent=`결과 열기: ${artifact.name}`;button.onclick=()=>openArtifact(artifact.id,artifact.name);node.append(button);}if(['queued','running','paused'].includes(job.status)){for(const action of job.status==='paused'?['resume','cancel']:['pause','cancel']){const button=document.createElement('button');button.textContent=action==='pause'?'일시정지':action==='resume'?'재개':'취소';button.onclick=()=>jobAction(job,action);node.append(button);}}return node;}));}
async function refresh(){if(!connection)return;try{state=await api<State>('/state');showMessage();render();}catch(error){showMessage(`연결 실패 — 마지막 화면을 유지합니다. ${String((error as Error).message)}`);}}
async function pair(event:SubmitEvent){event.preventDefault();showMessage();const origin=normalizeOrigin(($<HTMLInputElement>('origin')).value);const pairing=($<HTMLInputElement>('pairing')).value;vaultPassword=($<HTMLInputElement>('vault-password')).value;const response=await fetch(`${origin}/api/v1/devices/enroll`,{method:'POST',headers:{authorization:`Bearer ${pairing}`,'content-type':'application/json'},body:JSON.stringify({name:'YENO Android Controller',platform:'android',requestId:requestId()}),connectTimeout:10_000});const body=await response.json();if(!response.ok)throw new Error(body.error||`HTTP ${response.status}`);connection={origin,deviceId:body.device.id,token:body.device.deviceToken};await saveConnection(connection);localStorage.setItem(vaultMarker,'present');($<HTMLInputElement>('pairing')).value='';($<HTMLInputElement>('vault-password')).value='';await refresh();}
async function submit(event:SubmitEvent){event.preventDefault();const text=($<HTMLTextAreaElement>('text')).value.trim();if(!text)return;let pending=localStorage.getItem(requestKey);if(!pending){pending=JSON.stringify({text,requestId:requestId()});localStorage.setItem(requestKey,pending);}const body=JSON.parse(pending);$('pending').textContent='접수 확인 전에는 같은 요청 ID를 보존합니다.';await api('/commands',{method:'POST',body:JSON.stringify(body)});localStorage.removeItem(requestKey);$('pending').textContent='';($<HTMLTextAreaElement>('text')).value='';await refresh();}
async function jobAction(job:Job,action:string){await api(`/jobs/${encodeURIComponent(job.id)}/action`,{method:'POST',body:JSON.stringify({action,revision:job.version,requestId:requestId()})});await refresh();}
async function openArtifact(id:string,name:string){const response=await fetch(`${connection!.origin}/api/v1/artifacts/${encodeURIComponent(id)}`,{headers:{authorization:`Bearer ${connection!.token}`}});if(!response.ok)throw new Error(`결과를 열 수 없습니다: HTTP ${response.status}`);const text=await response.text();await navigator.clipboard.writeText(text);alert(`${name}\n\n${text}\n\n결과를 클립보드에 복사했습니다.`);}
async function globalStop(){await api('/control',{method:'POST',body:JSON.stringify({action:state?.emergencyStop?'resume':'stop',...(state?.emergencyStop?{revision:state.revision}:{}),requestId:requestId()})});await refresh();}
async function unlock(event:SubmitEvent){event.preventDefault();vaultPassword=($<HTMLInputElement>('unlock-password')).value;connection=await loadConnection();if(!connection)throw new Error('저장된 연결을 찾지 못했습니다.');($<HTMLInputElement>('unlock-password')).value='';render();await refresh();}
async function disconnect(){if(connection)try{await api('/devices/revoke',{method:'POST',body:JSON.stringify({requestId:requestId()})});}catch{/* Local removal must remain available if the server is unreachable. */}connection=null;state=null;localStorage.removeItem(requestKey);localStorage.removeItem(vaultMarker);await saveConnection(null);vaultPassword=null;render();}
function guard(task:()=>Promise<void>){void task().catch(error=>showMessage((error as Error).message));}
$('unlock-form').addEventListener('submit',event=>guard(()=>unlock(event as SubmitEvent)));$('pair').addEventListener('submit',event=>guard(()=>pair(event as SubmitEvent)));$('command').addEventListener('submit',event=>guard(()=>submit(event as SubmitEvent)));$('refresh').onclick=()=>guard(refresh);$('stop').onclick=()=>guard(globalStop);$('disconnect').onclick=()=>guard(disconnect);
window.addEventListener('visibilitychange',()=>{if(!document.hidden)guard(refresh);});
guard(async()=>{render();refreshTimer=window.setInterval(()=>{if(!document.hidden)guard(refresh);},3000);void refreshTimer;});
