import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {execFileSync} from 'node:child_process';
import {runDeveloperTask,headOf,dockerArguments,validateContract,DockerSandbox,snapshotRepository} from './worker.mjs';import {PATCH_SCHEMA,sha256} from '../../runtime/lib/repository-patch.mjs';
const code='export const sum = xs => 0;\n',fixed='export const sum = xs => xs.reduce((a,b)=>a+b,0);\n';
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'blackhole-worker-test-')),root=path.join(dir,'repo');fs.mkdirSync(path.join(root,'projects/demo'),{recursive:true});fs.writeFileSync(path.join(root,'projects/demo/main.mjs'),code);fs.writeFileSync(path.join(root,'projects/demo/main.test.mjs'),"import test from 'node:test';import assert from 'node:assert/strict';import {sum} from './main.mjs';test('positive',()=>assert.equal(sum([2,4]),6));test('empty',()=>assert.equal(sum([]),0));test('negative',()=>assert.equal(sum([-2,1]),-1));\n");execFileSync('git',['init','-q'],{cwd:root});execFileSync('git',['add','.'],{cwd:root});execFileSync('git',['-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-qm','baseline'],{cwd:root});const contract={id:'sum-fixture',baseCommit:headOf(root),goal:'Fix sum without changing tests',editablePaths:['projects/demo/main.mjs'],contextPaths:[],testFiles:['projects/demo/main.test.mjs']};t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return {dir,root,contract,journalPath:path.join(dir,'journal.json')};}
const patch=(task,content=fixed)=>({schema:PATCH_SCHEMA,baseCommit:task.baseCommit,changes:[{path:task.files[0].path,beforeSha256:task.files[0].sha256,content}]});
const result=(ok)=>({exitCode:ok?0:1,stdout:ok?'3 tests passed':'actual fixture test failure',stderr:'',timedOut:false,isolation:'synthetic-test-adapter'});
test('test failure feeds one repair, immutable tests and original source survive, replay makes no calls',async t=>{
 const f=fixture(t);let calls=0,runs=0,published=0;const sandbox={run:async({workspace})=>{runs++;const actual=fs.readFileSync(path.join(workspace,'projects/demo/main.mjs'),'utf8');return result(actual===fixed);}};
 const model=async task=>{calls++;if(calls===2)assert.match(task.feedback,/failure/);assert.equal(task.files[0].content,code);return patch(task,calls===1?'export const sum = xs => 1;\n':fixed);};
 const publish=async data=>{published++;assert.equal(data.evidence.attempts.length,2);assert.equal(data.evidence.phase,'publishing');return {url:'synthetic-private-pr'};};
 const j=await runDeveloperTask({...f,model,sandbox,publish});assert.equal(j.phase,'awaiting_approval',JSON.stringify(j));assert.equal(calls,2);assert.equal(runs,3);assert.equal(published,1);assert.equal(fs.readFileSync(path.join(f.root,'projects/demo/main.mjs'),'utf8'),code);
 assert.equal((await runDeveloperTask({...f,model,sandbox,publish})).phase,j.phase);assert.equal(calls,2);assert.equal(published,1);
});
test('no useful patch after two attempts does not publish',async t=>{const f=fixture(t);let n=0;const j=await runDeveloperTask({...f,model:async task=>{n++;return patch(task,'export const sum = xs => 7;');},sandbox:{run:async()=>result(false)},publish:async()=>assert.fail('must not publish')});assert.equal(j.phase,'failed');assert.equal(n,2);assert.equal(j.patch,undefined);});
test('lost model reply holds unknown reservation and restart cannot duplicate it',async t=>{const f=fixture(t);let n=0;const options={...f,model:async()=>{n++;throw Error('lost');},sandbox:{run:async()=>result(false)}};const a=await runDeveloperTask(options);assert.equal(a.phase,'unknown');assert.equal(a.attempts[0].status,'unknown');const b=await runDeveloperTask(options);assert.equal(b.phase,'unknown');assert.equal(n,1);});
test('stop stops before another model call and keeps a paused journal',async t=>{const f=fixture(t),abort=new AbortController();let n=0;const j=await runDeveloperTask({...f,signal:abort.signal,model:async task=>{n++;abort.abort();return patch(task);},sandbox:{run:async()=>result(false)}});assert.equal(j.phase,'paused');assert.equal(n,1);});
test('scope and safety controls cannot be changed by a task',t=>{const f=fixture(t);assert.throws(()=>validateContract({...f.contract,editablePaths:['runtime/lib/agent.mjs']}));assert.throws(()=>validateContract({...f.contract,testFiles:[]}));assert.throws(()=>validateContract({...f.contract,command:['sh','-c','true']}));});
test('same identity with different input is refused',async t=>{const f=fixture(t);const options={...f,model:async task=>patch(task),sandbox:{run:async()=>result(true)}};await runDeveloperTask(options);await assert.rejects(()=>runDeveloperTask({...options,contract:{...f.contract,goal:'different'}}),/identity_conflict/);});
test('untracked files, credential environment and .git are not copied',t=>{const f=fixture(t);fs.writeFileSync(path.join(f.root,'.env'),'secret');fs.writeFileSync(path.join(f.root,'untracked'),'secret');const dest=path.join(f.dir,'snapshot');snapshotRepository(f.root,f.contract.baseCommit,dest);assert.equal(fs.existsSync(path.join(dest,'.env')),false);assert.equal(fs.existsSync(path.join(dest,'untracked')),false);assert.equal(fs.existsSync(path.join(dest,'.git')),false);});
test('Docker command pins image, removes network/capabilities, mounts only source read-only',()=>{const args=dockerArguments({workspace:'/tmp/source',imageId:'sha256:'+'a'.repeat(64),name:'blackhole-11111111-1111-1111-1111-111111111111',testFiles:['projects/demo/main.test.mjs']});for(const v of ['none','--read-only','--cap-drop','ALL','no-new-privileges=true','1000:1000','--pids-limit','--memory'])assert.ok(args.includes(v));assert.ok(args.includes('type=bind,src=/tmp/source,dst=/workspace,readonly'));assert.equal(args.some(v=>/docker.sock|GITHUB_TOKEN|--privileged/.test(v)),false);assert.throws(()=>dockerArguments({workspace:'/tmp/x,src=/',imageId:'sha256:'+'a'.repeat(64),name:'blackhole-11111111-1111-1111-1111-111111111111',testFiles:['x.test.mjs']}));});
test('real Docker: broken repository -> failing candidate -> repaired tests -> approval, with no source overwrite',{skip:process.env.DEVELOPER_DOCKER_REQUIRED!=='1'},async t=>{
 const f=fixture(t),sandbox=new DockerSandbox({imageId:process.env.BLACKHOLE_WORKER_IMAGE_ID,timeoutMs:30000});let calls=0;const j=await runDeveloperTask({...f,sandbox,model:async task=>{calls++;return patch(task,calls===1?'export const sum = xs => 1;\n':fixed);}});assert.equal(j.phase,'candidate_verified',JSON.stringify(j));assert.equal(j.baseline.passed,false);assert.equal(j.attempts[0].test.passed,false);assert.equal(j.attempts[1].test.passed,true);assert.equal(calls,2);assert.equal(j.attempts[1].test.isolation,'docker-no-network');assert.equal(headOf(f.root),f.contract.baseCommit);
});
test('real Docker: host secrets/git unavailable, source read-only, non-root and timeout kill',{skip:process.env.DEVELOPER_DOCKER_REQUIRED!=='1'},async t=>{
 const f=fixture(t),workspace=path.join(f.dir,'probe');fs.mkdirSync(workspace);fs.chmodSync(f.dir,0o755);
 fs.writeFileSync(path.join(workspace,'probe.test.mjs'),"import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';test('isolation',()=>{assert.equal(process.getuid(),1000);assert.equal(process.env.BLACKHOLE_SYNTHETIC_HOST_SECRET,undefined);assert.equal(fs.existsSync('/workspace/.git'),false);assert.throws(()=>fs.writeFileSync('/workspace/should-not-exist','x'));});");process.env.BLACKHOLE_SYNTHETIC_HOST_SECRET='synthetic-only';
 const sandbox=new DockerSandbox({imageId:process.env.BLACKHOLE_WORKER_IMAGE_ID,timeoutMs:30000});const r=await sandbox.run({workspace,testFiles:['probe.test.mjs']});delete process.env.BLACKHOLE_SYNTHETIC_HOST_SECRET;assert.equal(r.exitCode,0,r.stdout+r.stderr);assert.equal(fs.existsSync(path.join(workspace,'should-not-exist')),false);
 fs.writeFileSync(path.join(workspace,'hang.test.mjs'),'while(true) {}');const limited=new DockerSandbox({imageId:process.env.BLACKHOLE_WORKER_IMAGE_ID,timeoutMs:2500});const h=await limited.run({workspace,testFiles:['hang.test.mjs']});assert.equal(h.timedOut,true);
});
